---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: "release"
  name: update-infra-deployments
spec:
  description: |-
    * This task clones a GitHub repository specified in the 'targetGHRepo' key of the input data file.
    * If 'targetGHRepo' is not provided, it defaults to 'defaultTargetGHRepo: redhat-appstudio/infra-deployments'.
    * It then runs a script obtained from the 'infra-deployment-update-script' key in the data file, which can modify text files.
    * Finally, it generates a pull request for the specified repository using the modified files.
  params:
    - name: dataJsonPath
      description: path to data json file
    - name: snapshotPath
      description: path to snapshot json file
    - name: defaultTargetGHRepo
      description: GitHub repository of the infra-deployments code
      default: redhat-appstudio/infra-deployments
    - name: defaultGithubAppID
      description: Default ID of Github app used for updating PR
      default: "305606"
    - name: defaultGithubAppInstallationID
      description: Default Installation ID of Github app in the organization
      default: "35269675"
    - name: sharedSecret
      default: infra-deployments-pr-creator
      description: secret in the namespace which contains private key for the GitHub App
    - name: ociStorage
      description: The OCI repository where the Trusted Artifacts are stored.
      type: string
      default: "empty"
    - name: ociArtifactExpiresAfter
      description: Expiration date for the trusted artifacts created in the OCI repository. An empty string means the artifacts do not expire
      type: string
      default: "1d"
    - name: trustedArtifactsDebug
      description: Flag to enable debug logging in trusted artifacts. Set to a non-empty string to enable.
      type: string
      default: ""
    - name: orasOptions
      description: oras options to pass to Trusted Artifacts calls
      type: string
      default: ""
    - name: sourceDataArtifact
      type: string
      description: Location of trusted artifacts to be used to populate data directory
      default: ""
    - name: dataDir
      description: The location where data will be stored
      type: string
      default: $(workspaces.data.path)
    - name: taskGitUrl
      type: string
      description: The url to the git repo where the release-service-catalog tasks and stepactions to be used are stored
    - name: taskGitRevision
      type: string
      description: The revision in the taskGitUrl repo to be used
  workspaces:
    - name: artifacts
      description: Workspace containing arbitrary artifacts used during the task run.
      optional: true
    - name: data
      description: The workspace where the snapshot spec json file resides
  results:
    - name: sourceDataArtifact
      type: string
      description: Produced trusted data artifact
  volumes:
    - name: infra-deployments-pr-creator
      secret:
        # 'private-key' - private key for Github app
        secretName: $(params.sharedSecret)
    - name: shared-dir
      emptyDir: {}
    - name: workdir
      emptyDir: {}
  stepTemplate:
    volumeMounts:
      - mountPath: /var/workdir
        name: workdir
    env:
      - name: IMAGE_EXPIRES_AFTER
        value: $(params.ociArtifactExpiresAfter)
      - name: "ORAS_OPTIONS"
        value: "$(params.orasOptions)"
      - name: "DEBUG"
        value: "$(params.trustedArtifactsDebug)"
  steps:
    - name: skip-trusted-artifact-operations
      computeResources:
        limits:
          memory: 32Mi
        requests:
          memory: 32Mi
          cpu: 20m
      ref:
        resolver: "git"
        params:
          - name: url
            value: $(params.taskGitUrl)
          - name: revision
            value: $(params.taskGitRevision)
          - name: pathInRepo
            value: stepactions/skip-trusted-artifact-operations/skip-trusted-artifact-operations.yaml
      params:
        - name: ociStorage
          value: $(params.ociStorage)
        - name: workDir
          value: $(params.dataDir)
    - name: use-trusted-artifact
      computeResources:
        limits:
          memory: 32Mi
        requests:
          memory: 32Mi
          cpu: 20m
      ref:
        resolver: "git"
        params:
          - name: url
            value: $(params.taskGitUrl)
          - name: revision
            value: $(params.taskGitRevision)
          - name: pathInRepo
            value: stepactions/use-trusted-artifact/use-trusted-artifact.yaml
      params:
        - name: workDir
          value: $(params.dataDir)
        - name: sourceDataArtifact
          value: $(params.sourceDataArtifact)
    - name: git-clone-infra-deployments
      image: quay.io/konflux-ci/release-service-utils:0077f4af29bb55cb80fcce770dd32f2e7bba97d7
      computeResources:
        limits:
          memory: 256Mi
        requests:
          memory: 256Mi
          cpu: 150m
      volumeMounts:
        - name: shared-dir
          mountPath: /shared
      workingDir: /shared
      script: |
        TARGET_GH_REPO="$(jq -r '.targetGHRepo // "$(params.defaultTargetGHRepo)"' \
          "$(params.dataDir)/$(params.dataJsonPath)")"
        echo "Cloning $TARGET_GH_REPO"
        git clone "https://github.com/${TARGET_GH_REPO}.git" cloned
    - name: run-update-script
      image: quay.io/konflux-ci/release-service-utils:0077f4af29bb55cb80fcce770dd32f2e7bba97d7
      computeResources:
        limits:
          memory: 128Mi
        requests:
          memory: 128Mi
          cpu: 100m
      volumeMounts:
        - name: shared-dir
          mountPath: /shared
      workingDir: /shared
      script: |
        #!/usr/bin/env bash
        set -ex
        cd cloned

        echo "snapshot:"
        cat "$(params.dataDir)/$(params.snapshotPath)"
        echo ""

        # We assume we only have one component in the service.
        revision="$(jq -r .components[0].source.git.revision "$(params.dataDir)/$(params.snapshotPath)")"
        echo "revision: $revision"
        echo "$revision" > ../revision.txt

        originRepo="$(jq -r .components[0].source.git.url "$(params.dataDir)/$(params.snapshotPath)")"
        echo "origin repo: $originRepo"
        echo "$originRepo" > ../originRepo.txt

        # Get SCRIPT from Data
        echo "data: $(params.dataDir)/$(params.dataJsonPath)"
        SCRIPT="$(jq -r '."infra-deployment-update-script" // empty' "$(params.dataDir)/$(params.dataJsonPath)")"

        if [ "${SCRIPT}" == "" ] ; then
          echo "No script provided via 'infra-deployment-update-script' key in data"
          exit 0
        fi

        echo "original script:"
        echo "$SCRIPT"
        PATCHED_SCRIPT="${SCRIPT//\{\{ revision \}\}/$revision}"
        echo "patched script:"
        echo "$PATCHED_SCRIPT"
        echo "$PATCHED_SCRIPT" | sh
    - name: get-diff-files
      image: quay.io/konflux-ci/release-service-utils:0077f4af29bb55cb80fcce770dd32f2e7bba97d7
      computeResources:
        limits:
          memory: 128Mi
        requests:
          memory: 128Mi
          cpu: 100m
      volumeMounts:
        - name: shared-dir
          mountPath: /shared
      workingDir: /shared
      script: |
        cd cloned
        git status -s --porcelain | cut -c4- > ../updated_files.txt
    # Based on https://github.com/tektoncd/catalog/tree/main/task/github-app-token/0.2/
    - name: create-pr
      image: quay.io/konflux-ci/release-service-utils:0077f4af29bb55cb80fcce770dd32f2e7bba97d7
      computeResources:
        limits:
          memory: 512Mi
        requests:
          memory: 512Mi
          cpu: 350m
      volumeMounts:
        - name: infra-deployments-pr-creator
          mountPath: /secrets/deploy-key
        - name: shared-dir
          mountPath: /shared
      workingDir: /shared
      env:
        - name: GITHUBAPP_KEY_PATH
          value: /secrets/deploy-key/private-key
        - name: GITHUB_API_URL
          value: https://api.github.com
        - name: DATA_JSON_PATH
          value: "$(params.dataDir)/$(params.dataJsonPath)"
        - name: DEFAULT_TARGET_GH_REPO
          value: "$(params.defaultTargetGHRepo)"
        - name: DEFAULT_GITHUB_APP_ID
          value: "$(params.defaultGithubAppID)"
        - name: DEFAULT_GITHUB_APP_INSTALLATION_ID
          value: "$(params.defaultGithubAppInstallationID)"
      script: "#!/usr/bin/env python3\nimport json\nimport os\nimport sys\nimport time\nimport base64\nimport requests\nimport subprocess\n\nEXPIRE_MINUTES_AS_SECONDS = int(os.environ.get('GITHUBAPP_TOKEN_EXPIRATION_MINUTES', 10)) * 60\n# TODO support github enteprise\nGITHUB_API_URL = os.environ.get('GITHUB_API_URL')\n\n# Fetch targetGHRepo, githubAppID, and githubAppInstallationID from data JSON file\nwith open(os.environ.get('DATA_JSON_PATH'), 'r') as f:\n    data = json.load(f)\n    target_gh_repo = data.get(\n        'targetGHRepo',\n        os.environ.get('DEFAULT_TARGET_GH_REPO')\n    )\n    github_app_id = str(data.get(\n        'githubAppID',\n        os.environ.get('DEFAULT_GITHUB_APP_ID')\n    ))\n    github_app_installation_id = str(data.get(\n        'githubAppInstallationID',\n        os.environ.get('DEFAULT_GITHUB_APP_INSTALLATION_ID')\n    ))\n    os.environ['TARGET_GH_REPO'] = target_gh_repo\n    os.environ['GITHUBAPP_APP_ID'] = github_app_id\n    os.environ['GITHUBAPP_INSTALLATION_ID'] = github_app_installation_id\n\nwith open('originRepo.txt', 'r') as fileA:\n  originRepo = fileA.read().rstrip()\nwith open('revision.txt', 'r') as fileB:\n  revision = fileB.read().rstrip()\n\nclass GitHub():\n    token = None\n\n    def __init__(self, private_key_path, app_id=None, installation_id=None):\n        self._private_key_path = private_key_path\n        self.app_id = app_id\n        self.token = self._get_token(installation_id)\n\n    def _app_token(self, expire_in=EXPIRE_MINUTES_AS_SECONDS):\n      # based on https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/\n      # generating-a-json-web-token-jwt-for-a-github-app#example-using-bash-to-generate-a-jwt\n\n        now = int(time.time())\n\n        header_ = {\"typ\": \"JWT\", \"alg\": \"RS256\"}\n        header = base64.b64encode(json.dumps(header_).encode())\n\n        payload_ = {\"iat\": now, \"exp\": now + expire_in, \"iss\": self.app_id}\n        payload = base64.b64encode(json.dumps(payload_).encode())\n\n        header_payload = header + b\".\" + payload\n        proc = subprocess.run(\n            [\"openssl\", \"dgst\", \"-sha256\", \"-sign\", self._private_key_path],\n            input=header_payload,\n            check=True,\n            stdout=subprocess.PIPE,\n        )\n        signature = base64.b64encode(proc.stdout)\n\n        token = header_payload + b\".\" + signature\n        return token.decode()\n\n    def _get_token(self, installation_id=None):\n        app_token = self._app_token()\n        if not installation_id:\n            return app_token\n\n        req = self._request(\n            \"POST\",\n            f\"/app/installations/{installation_id}/access_tokens\",\n            headers={\n                \"Authorization\": f\"Bearer {app_token}\",\n                \"Accept\": \"application/vnd.github.machine-man-preview+json\"\n            })\n\n        ret = req.json()\n        if 'token' not in ret:\n            raise Exception(f\"Authentication errors: {ret}\")\n\n        return ret['token']\n\n    def _request(self, method, url, headers={}, data={}):\n        if self.token and 'Authorization' not in headers:\n            headers.update({\"Authorization\": \"Bearer \" + self.token})\n        if not url.startswith(\"http\"):\n            url = f\"{GITHUB_API_URL}{url}\"\n        return requests.request(method,\n                                url,\n                                headers=headers,\n                                data=json.dumps(data))\n\n    def create_mr(self):\n        repo_name = originRepo.split('/')[-1]\n        target_gh_repo = os.environ.get('TARGET_GH_REPO')\n        req = self._request(\n            \"POST\",\n            f\"/repos/{target_gh_repo}/pulls\",\n            headers={\n                \"Authorization\": f\"Bearer {self.token}\",\n                \"Accept\": \"application/vnd.github.v3+json\"\n            },\n            data={\n                \"head\": repo_name,\n                \"base\": \"main\",\n                \"title\": f\"{repo_name} update\",\n                \"maintainer_can_modify\": False\n            })\n        json_output = req.json()\n        print(json_output)\n        return json_output\n\n    def create_reset_branch(self):\n        branch = originRepo.split('/')[-1]\n        target_gh_repo = os.environ.get('TARGET_GH_REPO')\n        target_branch = self._request(\"GET\", f\"/repos/{target_gh_repo}/git/refs/heads/{branch}\").json()\n        main_branch_sha = self._request(\"GET\", f\"/repos/{target_gh_repo}/git/refs/heads/main\")\\\n                          .json()['object']['sha']\n        if \"ref\" in target_branch:\n            # update branch\n            self._request(\n                \"PATCH\",\n                f\"/repos/{target_gh_repo}/git/refs/heads/{branch}\",\n                data={\"sha\": main_branch_sha, \"force\": True}\n            )\n        else:\n            # create branch\n            self._request(\n                \"POST\",\n                f\"/repos/{target_gh_repo}/git/refs\",\n                data={\"sha\": main_branch_sha, \"ref\": f\"refs/heads/{branch}\"}\n            )\n\n    def upload_content(self):\n        branch = originRepo.split('/')[-1]\n        target_gh_repo = os.environ.get('TARGET_GH_REPO')\n        for file in open('updated_files.txt').readlines():\n            file = file.strip()\n            with open(f\"cloned/{file}\", \"rb\") as fd:\n                encoded_string = base64.b64encode(fd.read()).decode(\"utf-8\")\n            old_sha = self._request(\"GET\", f'/repos/{target_gh_repo}/contents/{file}').json().get(\"sha\")\n            if old_sha is None:\n                self._request(\"PUT\", f'/repos/{target_gh_repo}/contents/{file}', \\\n                  data={\"message\": f\"update {file}\", \"branch\": branch, \"content\": encoded_string})\n            else:\n                self._request(\"PUT\", f'/repos/{target_gh_repo}/contents/{file}', \\\n                  data={\"message\": f\"update {file}\", \"branch\": branch, \\\n                  \"content\": encoded_string, \"sha\": old_sha})\n\n    def get_pr(self):\n        repo_name = originRepo.split('/')[-1]\n        target_gh_repo = os.environ.get('TARGET_GH_REPO')\n        req = self._request(\n            \"GET\",\n            f\"/repos/{target_gh_repo}/pulls\",\n            headers={\n                \"Accept\": \"application/vnd.github.v3+json\"\n            })\n        json_output = req.json()\n        for item in json_output:\n            if item[\"user\"][\"login\"].endswith(\"[bot]\") and item[\"head\"][\"ref\"] == repo_name:\n                return item\n\n    def get_pr_url_from_sha(self, sha):\n        req = self._request(\n            \"GET\",\n            f\"/search/issues?q={sha}\",\n            headers={\n                \"Accept\": \"application/vnd.github.v3+json\"\n            })\n        return req.json()[\"items\"][0][\"pull_request\"][\"html_url\"]\n\n    def update_mr_description(self, pr_url, description):\n        req = self._request(\n            \"PATCH\",\n            pr_url,\n            headers={\n                \"Authorization\": f\"Bearer {self.token}\",\n                \"Accept\": \"application/vnd.github.v3+json\"\n            },\n            data={ \"body\": description })\n        json_output = req.json()\n        print(json_output)\n\ndef main():\n\n    with open(\"updated_files.txt\", 'r') as ufiles:\n        updated_files = len(ufiles.readlines())\n    print('Total Number of updated files: ', updated_files)\n    if updated_files == 0:\n        print(\"No files to add to a PR. exiting...\")\n        sys.exit()\n\n    key_path = os.environ.get('GITHUBAPP_KEY_PATH')\n                \n    if os.environ.get('GITHUBAPP_APP_ID'):\n        app_id = os.environ['GITHUBAPP_APP_ID']\n    else:\n        raise Exception(\"application id is not set\")\n\n    print(f\"Getting user token for application_id: {app_id}\")\n    github_app = GitHub(\n        private_key_path=key_path,\n        app_id=app_id,\n        installation_id=os.environ.get('GITHUBAPP_INSTALLATION_ID'))\n\n    github_app.create_reset_branch()\n    github_app.upload_content()\n    infra_pr = github_app.create_mr()\n    if \"url\" not in infra_pr:\n        infra_pr = github_app.get_pr()\n    if \"body\" in infra_pr:\n        description = infra_pr[\"body\"]\n        if description is None:\n            description = \"Included PRs:\"\n        new_pr_link = github_app.get_pr_url_from_sha(revision)\n        new_description = f\"{description}\\r\\n- {new_pr_link}\"\n        github_app.update_mr_description(infra_pr[\"url\"], new_description)\n    else:\n        if \"message\" in infra_pr:\n            print(infra_pr[\"message\"])\n        raise Exception(\"PR not created or did not already exist\")\n\nif __name__ == '__main__':\n    main()\n"
    - name: create-trusted-artifact
      computeResources:
        limits:
          memory: 128Mi
        requests:
          memory: 128Mi
          cpu: 250m
      ref:
        resolver: "git"
        params:
          - name: url
            value: $(params.taskGitUrl)
          - name: revision
            value: $(params.taskGitRevision)
          - name: pathInRepo
            value: stepactions/create-trusted-artifact/create-trusted-artifact.yaml
      params:
        - name: ociStorage
          value: $(params.ociStorage)
        - name: workDir
          value: $(params.dataDir)
        - name: sourceDataArtifact
          value: $(results.sourceDataArtifact.path)
    - name: patch-source-data-artifact-result
      computeResources:
        limits:
          memory: 32Mi
        requests:
          memory: 32Mi
          cpu: 20m
      ref:
        resolver: "git"
        params:
          - name: url
            value: $(params.taskGitUrl)
          - name: revision
            value: $(params.taskGitRevision)
          - name: pathInRepo
            value: stepactions/patch-source-data-artifact-result/patch-source-data-artifact-result.yaml
      params:
        - name: ociStorage
          value: $(params.ociStorage)
        - name: sourceDataArtifact
          value: $(results.sourceDataArtifact.path)
