---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: pulp-push-disk-images
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: release
spec:
  description: |-
    Tekton task to push disk images with Pulp
  params:
    - name: snapshot_json
      type: string
      description: String containing a JSON representation of the snapshot spec
    - name: concurrentLimit
      type: string
      description: The maximum number of images to be pulled at once
      default: 3
    - name: exodusGwSecret
      type: string
      description: Env specific secret containing the Exodus Gateway configs
    - name: exodusGwEnv
      type: string
      description: Environment to use in the Exodus Gateway. Options are [live, pre]
    - name: pulpSecret
      type: string
      description: Env specific secret containing the rhsm-pulp credentials
    - name: udcacheSecret
      type: string
      description: Env specific secret containing the udcache credentials
    - name: cgwHostname
      type: string
      description: Env specific hostname for content gateway
    - name: cgwSecret
      type: string
      description: Env specific secret containing the content gateway credentials
  results:
    - name: result
      description: Success if the task succeeds, the error otherwise
  steps:
    - name: pull-and-push-images
      image: quay.io/konflux-ci/release-service-utils:597145c2cbcff9e99e1c62169eccab003e68c157
      computeResources:
        limits:
          memory: 512Mi
        requests:
          memory: 512Mi
          cpu: 450m
      env:
        - name: EXODUS_CERT
          valueFrom:
            secretKeyRef:
              name: $(params.exodusGwSecret)
              key: cert
        - name: EXODUS_KEY
          valueFrom:
            secretKeyRef:
              name: $(params.exodusGwSecret)
              key: key
        - name: EXODUS_URL
          valueFrom:
            secretKeyRef:
              name: $(params.exodusGwSecret)
              key: url
        - name: PULP_URL
          valueFrom:
            secretKeyRef:
              name: $(params.pulpSecret)
              key: pulp_url
        - name: PULP_CERT
          valueFrom:
            secretKeyRef:
              name: $(params.pulpSecret)
              key: konflux-release-rhsm-pulp.crt
        - name: PULP_KEY
          valueFrom:
            secretKeyRef:
              name: $(params.pulpSecret)
              key: konflux-release-rhsm-pulp.key
        - name: UDC_URL
          valueFrom:
            secretKeyRef:
              name: $(params.udcacheSecret)
              key: url
        - name: UDC_CERT
          valueFrom:
            secretKeyRef:
              name: $(params.udcacheSecret)
              key: cert
        - name: UDC_KEY
          valueFrom:
            secretKeyRef:
              name: $(params.udcacheSecret)
              key: key
        - name: DOCKER_CONFIG_JSON
          valueFrom:
            secretKeyRef:
              name: redhat-workloads-token
              key: .dockerconfigjson
        - name: "SNAPSHOT_JSON"
          value: "$(params.snapshot_json)"
        - name: CGW_USERNAME
          valueFrom:
            secretKeyRef:
              name: $(params.cgwSecret)
              key: username
        - name: CGW_PASSWORD
          valueFrom:
            secretKeyRef:
              name: $(params.cgwSecret)
              key: token
      script: "#!/usr/bin/env bash\nset -ex\n\nSTDERR_FILE=/tmp/stderr.txt\n\nexitfunc() {\n    local err=$1\n    local line=$2\n    local command=\"$3\"\n    if [ \"$err\" -eq 0 ] ; then\n        echo -n \"Success\" > \"$(results.result.path)\"\n    else\n        echo \"$0: ERROR '$command' failed at line $line - exited with status $err\" \\\n          > \"$(results.result.path)\"\n        if [ -f \"$STDERR_FILE\" ] ; then\n            tail -n 20 \"$STDERR_FILE\" >> \"$(results.result.path)\"\n        fi\n    fi\n    exit 0 # exit the script cleanly as there is no point in proceeding past an error or exit call\n}\n# due to set -e, this catches all EXIT and ERR calls and the task should never fail with nonzero exit code\ntrap 'exitfunc $? $LINENO \"$BASH_COMMAND\"' EXIT\n\n# Setup required variables\nexport EXODUS_GW_CERT=/tmp/exodus.crt\nexport EXODUS_GW_KEY=/tmp/exodus.key\nexport PULP_CERT_FILE=/tmp/pulp.crt\nexport PULP_KEY_FILE=/tmp/pulp.key\nexport UDCACHE_CERT=/tmp/udc.crt\nexport UDCACHE_KEY=/tmp/udc.key\nEXODUS_GW_ENV=$(params.exodusGwEnv)\nexport EXODUS_GW_ENV\nexport EXODUS_GW_URL=\"$EXODUS_URL\"\nexport EXODUS_PULP_HOOK_ENABLED=True\nexport EXODUS_GW_TIMEOUT=7200\nmkdir -p ~/.docker\n\nset +x\necho \"$EXODUS_CERT\" > \"$EXODUS_GW_CERT\"\necho \"$EXODUS_KEY\" > \"$EXODUS_GW_KEY\"\necho \"$PULP_CERT\" > \"$PULP_CERT_FILE\"\necho \"$PULP_KEY\" > \"$PULP_KEY_FILE\"\necho \"$UDC_CERT\" > \"$UDCACHE_CERT\"\necho \"$UDC_KEY\" > \"$UDCACHE_KEY\"\n# Quotes are added to the secret so it applies in k8s nicely. But now we have to remove them\necho \"$DOCKER_CONFIG_JSON\" | sed -r 's/(^|\\})[^{}]+(\\{|$)/\\1\\2/g' > ~/.docker/config.json\nset -x\n\nDISK_IMAGE_DIR=\"$(mktemp -d)\"\nexport DISK_IMAGE_DIR\n\nprocess_component() { # Expected argument is [component json]\n    COMPONENT=$1\n    PULLSPEC=$(jq -er '.containerImage' <<< \"${COMPONENT}\")\n    DESTINATION=\"${DISK_IMAGE_DIR}/$(jq -er '.staged.destination' <<< \"${COMPONENT}\")/FILES\" \\\n      || (echo \"Missing staged.destination value for component. This should be an existing pulp repo. \\\n          Failing\" && exit 1)\n    mkdir -p \"${DESTINATION}\"\n    DOWNLOAD_DIR=$(mktemp -d)\n    cd \"$DOWNLOAD_DIR\"\n    # oras has very limited support for selecting the right auth entry,\n    # so create a custom auth file with just one entry\n    AUTH_FILE=$(mktemp)\n    select-oci-auth \"${PULLSPEC}\" > \"$AUTH_FILE\"\n    oras pull --registry-config \"$AUTH_FILE\" \"$PULLSPEC\"\n    NUM_MAPPED_FILES=$(jq '.staged.files | length' <<< \"${COMPONENT}\")\n    for ((i = 0; i < NUM_MAPPED_FILES; i++)) ; do\n        FILE=$(jq -c --arg i \"$i\" '.staged.files[$i|tonumber]' <<< \"$COMPONENT\")\n        SOURCE=$(jq -er '.source' <<< \"$FILE\")\n        FILENAME=$(jq -er '.filename' <<< \"$FILE\")\n        # The .qcow2 images are not zipped\n        if [ -f \"${SOURCE}.gz\" ] ; then\n            gzip -d \"${SOURCE}.gz\"\n        fi\n        DESTINATION_FILE=\"${DESTINATION}/${FILENAME}\"\n        # Albeit a rare one, this is a race condition since this is run in parallel.\n        # The race condition is if two files have the same $DESTINATION_FILE and both\n        # if checks are run before either mv is run a few lines below.\n        if [ -f \"${DESTINATION_FILE}\" ] ; then\n            echo -n \"Multiple files use the same destination value: $DESTINATION\" >&2\n            echo \" and filename value: $FILENAME. Failing...\" >&2\n            exit 1\n        fi\n        mv \"$SOURCE\" \"${DESTINATION_FILE}\" || echo \"didn't find mapped file: ${SOURCE}\"\n    done\n\n}\n\nprocess_component_for_developer_portal() { # Expected argument are [component json], [content_directory]\n  COMPONENT=$1\n\n  productName=\"$(jq -er '.contentGateway.productName' <<< \"${COMPONENT}\")\" \\\n    || (echo \"Missing contentGateway.productName value for component. This should be an existing product \\\n          in the Developer Portal. Failing\" && exit 1)\n\n  productCode=\"$(jq -er '.contentGateway.productCode' <<< \"${COMPONENT}\")\" \\\n    || (echo \"Missing contentGateway.productCode value for component. This should be an existing product \\\n          in the Developer Portal. Failing\" && exit 1)\n\n  productVersionName=\"$(jq -er '.contentGateway.productVersionName' <<< \"${COMPONENT}\")\" \\\n    || (echo \"Missing contentGateway.productVersionName value for component. This should be an existing \\\n          product in the Developer Portal. Failing\" && exit 1)\n\n  filePrefix=\"$(jq -er '.contentGateway.filePrefix' <<< \"${COMPONENT}\")\" \\\n    || (echo \"Missing contentGateway.filePrefix value for component. This should be the prefix for files to \\\n          upload to the Developer Portal. Failing\" && exit 1)\n\n  developer_portal_wrapper --debug --product-name \"${productName}\" \\\n    --product-code \"${productCode}\" \\\n    --product-version-name \"${productVersionName}\" \\\n    --cgw-hostname \"$(params.cgwHostname)\" \\\n    --content-directory \"$2\" \\\n    --file-prefix \"${filePrefix}\"\n\n}\n\nRUNNING_JOBS=\"\\j\" # Bash parameter for number of jobs currently running\nNUM_COMPONENTS=$(jq '.components | length' <<< \"$SNAPSHOT_JSON\")\n\n# use the 1st component's version\nVERSION=$(jq -cr '.components[0].staged.version // \"\"' <<< \"$SNAPSHOT_JSON\")\nif [ \"${VERSION}\" == \"\" ] ; then\n  echo \"Error: version not specified in .components[0].staged.version. Needed to publish to customer portal\"\n  exit 1\nfi\n\n# Process each component in parallel\nfor ((i = 0; i < NUM_COMPONENTS; i++)) ; do\n    COMPONENT=$(jq -c --arg i \"$i\" '.components[$i|tonumber]' <<< \"$SNAPSHOT_JSON\")\n    # Limit batch size to concurrent limit\n    while (( ${RUNNING_JOBS@P} >= $(params.concurrentLimit) )); do\n        wait -n\n    done\n    process_component \"$COMPONENT\" 2> \"$STDERR_FILE\" &\ndone\n\n# Wait for remaining processes to finish\nwhile (( ${RUNNING_JOBS@P} > 0 )); do\n    wait -n\ndone\n\n# Change to the subdir with the images\ncd \"${DISK_IMAGE_DIR}\"\n\nSTAGED_JSON='{\"header\":{\"version\": \"0.2\"},\"payload\":{\"files\":[]}}'\n\n# Add the files to the payload\n# shell check wants us to find ./* but that adds `./` to the paths which breaks the script\n# shellcheck disable=SC2035\nwhile IFS= read -r -d '' file ; do\n    STAGED_JSON=$(jq --arg filename \"$(basename \"$file\")\" --arg path \"$file\" \\\n      --arg version \"$VERSION\" \\\n      '.payload.files[.payload.files | length] = \n      {\"filename\": $filename, \"relative_path\": $path, \"version\": $version}' <<< \"$STAGED_JSON\")\ndone < <(find * -type f -print0)\n\necho \"$STAGED_JSON\" | yq -P -I 4 > staged.yaml\n\npulp_push_wrapper --debug --source \"${DISK_IMAGE_DIR}\" --pulp-url \"$PULP_URL\" \\\n  --pulp-cert $PULP_CERT_FILE --pulp-key $PULP_KEY_FILE --udcache-url \"$UDC_URL\" \\\n  2> \"$STDERR_FILE\"\n\nrelative_paths=$(echo \"$STAGED_JSON\" | jq -erc .payload.files[].relative_path)\ncomponent_destinations=()\nfor path in $relative_paths:\ndo\n  parent_dir=$(dirname \"$path\")\n  component_destinations+=(\"${DISK_IMAGE_DIR}/$parent_dir\")\ndone\n\n## Process Files for Developer Portal / CGW\n##\nNUM_COMPONENTS=$(jq '.components | length' <<< \"$SNAPSHOT_JSON\")\nfor ((i = 0; i < NUM_COMPONENTS; i++)) ; do\n    COMPONENT=$(jq -c --arg i \"$i\" '.components[$i|tonumber]' <<< \"$SNAPSHOT_JSON\")\n    process_component_for_developer_portal \"$COMPONENT\" \"${component_destinations[$i]}\"  2> \"$STDERR_FILE\"\ndone\n"
